### Create Product
POST http://localhost:8080/api/product
Content-Type: application/octet-stream
Accept: application/json

{
    "name": "Mie Ayam",
    "price": 3000,
    "stock": 200,
    "category_id": 1
}

### Create Category
POST http://localhost:8080/api/category
Content-Type: application/octet-stream
Accept: application/json

{
    "name": "Drink",
    "description": "minuman"
}

### Update Category
PUT http://localhost:8080/api/category/1
Content-Type: application/octet-stream
Accept: application/json

{
    "name": "Makanan Update",
    "description": "makanan"
}

### Update Product
PUT http://localhost:8080/api/product/1
Content-Type: application/octet-stream
Accept: application/json

{
    "name": "Soto update",
    "price": 4000,
    "stock": 500,
    "category_id": 1
}

### get All Product
GET http://localhost:8080/api/product
Content-Type: application/octet-stream
Accept: application/json

### get All Category
GET http://localhost:8080/api/category
Content-Type: application/octet-stream
Accept: application/json

### get Detail Product
GET http://localhost:8080/api/product/1
Content-Type: application/octet-stream
Accept: application/json

### get Detail Category
GET http://localhost:8080/api/category/1
Content-Type: application/octet-stream
Accept: application/json

### delete Product
DELETE  http://localhost:8080/api/product/1
Content-Type: application/octet-stream
Accept: application/json

### Create Category
POST http://localhost:8080/api/category
Content-Type: application/octet-stream
Accept: application/json

{
    "name": "Pakaian",
    "description": "baju dan celana"
}

### Update Category
PUT http://localhost:8080/api/category/3
Content-Type: application/octet-stream
Accept: application/json

{
    "name": "Pakaian Pria",
    "description": "pakaian pria"
}

### get All Category
GET http://localhost:8080/api/category
Content-Type: application/octet-stream
Accept: application/json

### get Detail Category
GET http://localhost:8080/api/category/3
Content-Type: application/octet-stream
Accept: application/json

### delete Category
DELETE  http://localhost:8080/api/category/1
Content-Type: application/octet-stream
Accept: application/json